Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2024-03, with the labels that each got.

#101 Added OpenAPI file generation for phoenix backend to allow for client generation
  solardoc/frontend/package.json
  solardoc/frontend/src/services/backend/api-service.ts
  solardoc/frontend/src/services/backend/gen/backend-rest-service.ts
  solardoc/frontend/src/services/phoenix/api-service.ts
  solardoc/frontend/src/services/phoenix/config.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/phoenix-server/config/config.exs
  solardoc/phoenix-server/lib/solardoc_phoenix_web.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/user_socket.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_accounts_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_auth_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_auth_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_registration_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_registration_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_reset_password_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_session_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_settings_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/home/home_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/user/user_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/user_auth.ex
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/mix.lock
  solardoc/phoenix-server/package.json
  solardoc/phoenix-server/priv/static/swagger.json
  solardoc/phoenix-server/test/solardoc_phoenix_web/controllers/user_registration_controller_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix_web/controllers/user_reset_password_controller_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix_web/controllers/user_session_controller_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix_web/controllers/user_settings_controller_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix_web/user_auth_test.exs
Labels: enhancement

#103 Fixed chrome gradient issue
  solardoc/frontend/src/views/HomeView.vue
Labels: fix

#102 Implemented password form for joining channels
  solardoc/frontend/src/components/channel-view/ChannelViewJoinConfirm.vue
Labels: enhancement

#115 Fixed Vueform bug throwing axios error every time the form is submitted
  solardoc/frontend/src/components/editor/channel-view/ChannelViewCreate.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelViewJoinConfirm.vue
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/SignupView.vue
Labels: bug, fix, skip changelog

#119 Implemented basic change pools where users can join and receive editor changes
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
Labels: enhancement
