Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2024-06, with the labels that each got.

#156 Fixed loading spinner appearing with a delay after pressing the homepage buttons
  solardoc/frontend/src/views/HomeView.vue
Labels: bug, fix

#157 Fixed editor cursor state bug in Chrome (0.6.x)
  README.adoc
  docker-compose-prod.yaml
  images/android-chrome-192x192.png
  images/android-chrome-512x512.png
  images/apple-touch-icon.png
  images/favicon-128x128.png
  images/favicon-48x48.png
  images/favicon.ico
  solardoc/frontend/public/android-chrome-192x192.png
  solardoc/frontend/public/android-chrome-512x512.png
  solardoc/frontend/public/apple-touch-icon.png
  solardoc/frontend/public/favicon-128x128.png
  solardoc/frontend/public/favicon-48x48.png
  solardoc/frontend/public/favicon.ico
  solardoc/frontend/public/site.webmanifest
  solardoc/frontend/src/components/editor/Editor.vue
  traefik/docker-compose.yaml
Labels: bug, fix

#159 v0.6.2
  solardoc/frontend/src/components/editor/Editor.vue
Labels: release

#163 Fixed ShareURL pop-up style error
  README.adoc
  docker-compose-prod.yaml
  images/android-chrome-192x192.png
  images/android-chrome-512x512.png
  images/apple-touch-icon.png
  images/favicon-128x128.png
  images/favicon-48x48.png
  images/favicon.ico
  solardoc/frontend/public/android-chrome-192x192.png
  solardoc/frontend/public/android-chrome-512x512.png
  solardoc/frontend/public/apple-touch-icon.png
  solardoc/frontend/public/favicon-128x128.png
  solardoc/frontend/public/favicon-48x48.png
  solardoc/frontend/public/favicon.ico
  solardoc/frontend/public/site.webmanifest
  solardoc/frontend/src/components/editor/share-url/ShareUrlCreate.vue
  traefik/docker-compose.yaml
Labels: bug

#165 Changed color for headings in the editor
  solardoc/frontend/src/scripts/editor/monaco-config/dark-editor-theme.ts
Labels: fix

#169 Made file name read-only in opened share files
  solardoc/frontend/src/views/EditorView.vue
Labels: bug, fix

#170 Fixed last modified not being updated with remote updates
  solardoc/frontend/src/stores/current-file.ts
Labels: bug, fix

#174 Added check in ShareURLView.vue to avoid the owner viewing their own file as if they were a guest
  solardoc/frontend/src/views/ShareURLView.vue
Labels: bug, fix

#173 v0.7.1
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/ShareURLView.vue
Labels: release

#179 Implemented `returnTo` query parameter which will after a successful login redirect to the given page
  solardoc/frontend/src/scripts/is-valid-path.ts
  solardoc/frontend/src/views/LoginView.vue
Labels: enhancement

#181 Implemented search bar functionality for file viewer in the profile page
  solardoc/frontend/src/components/profile-view/file-view/FilesList.vue
  solardoc/frontend/src/components/profile-view/file-view/ProfileFileOverview.vue
  solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue
Labels: enhancement

#183 Fixed bug of user not being redirected to the editor after logging in to access a share URL
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/profile-view/file-view/FilesList.vue
  solardoc/frontend/src/components/profile-view/file-view/ProfileFileOverview.vue
  solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue
  solardoc/frontend/src/scripts/editor/sds.ts
  solardoc/frontend/src/scripts/is-valid-path.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/ShareURLView.vue
Labels: bug, fix

#184 Fixed bug of first time visitors incorrectly getting saved remotely shown as the file status
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/stores/current-file.ts
Labels: bug, fix

#186 Fixed file switching state inconsistency issues with the render data and websocket connection
  solardoc/frontend/src/components/editor/slides-navigator/SlidePreview.vue
  solardoc/frontend/src/components/editor/slides-navigator/SlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SlideSubSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SlideSubSlidesPreview.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SubSlidesNavigator.vue
  solardoc/frontend/src/components/profile-view/file-view/FileCard.vue
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/file.ts
  solardoc/frontend/src/scripts/handle-render.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/stores/editor-update-ws-client.ts
  solardoc/frontend/src/stores/init-state.ts
  solardoc/frontend/src/stores/render-data.ts
  solardoc/frontend/src/views/EditorView.vue
Labels: bug, fix

#187 Fixed password manager field detection bugs in login & register forms
  solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/SignupView.vue
Labels: bug, fix

#194 Fixed file still present in the editor after being deleted bug
  solardoc/frontend/src/components/profile-view/file-view/FileCard.vue
Labels: bug, fix

#197 Fixed bug where the full screen preview gets minimised after clicking on the full screen preview again
  package.json
  solardoc/asciidoc-renderer/package.json
  solardoc/asciidoc-renderer/src/index.ts
  solardoc/frontend/package.json
  solardoc/frontend/src/App.vue
  solardoc/frontend/src/components/editor/FullScreenPreview.vue
  solardoc/frontend/src/components/editor/LoadAnywayButton.vue
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/editor/slides-navigator/SlidePreview.vue
  solardoc/frontend/src/components/editor/slides-navigator/SlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SlideSubSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SlideSubSlidesPreview.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SubSlidesNavigator.vue
  solardoc/frontend/src/components/profile-view/file-view/FileCard.vue
  solardoc/frontend/src/components/profile-view/file-view/FilesList.vue
  solardoc/frontend/src/components/profile-view/file-view/ProfileFileOverview.vue
  solardoc/frontend/src/components/profile-view/file-view/SearchBar.vue
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/file.ts
  solardoc/frontend/src/scripts/editor/sds.ts
  solardoc/frontend/src/scripts/handle-render.ts
  solardoc/frontend/src/scripts/is-valid-path.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/stores/editor-update-ws-client.ts
  solardoc/frontend/src/stores/init-state.ts
  solardoc/frontend/src/stores/render-data.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/ShareURLView.vue
  solardoc/frontend/src/views/SignupView.vue
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/package.json
  solardoc/rest-api/package.json
Labels: bug, fix

#199 Fixed bug where the full screen preview gets minimised after clicking on the full screen preview again
  solardoc/frontend/src/components/editor/FullScreenPreview.vue
  solardoc/frontend/src/components/editor/LoadAnywayButton.vue
  solardoc/frontend/src/views/EditorView.vue
Labels: bug, fix

#207 Fixed bug that files larger than 255 bytes can't be uploaded or saved to the DB
  solardoc/phoenix-server/priv/repo/migrations/20240620091923_remove_file_content_length_limit.exs
  solardoc/phoenix-server/priv/repo/migrations/20240620093347_make_file_name_required.exs
Labels: bug, fix

#208 Migrated all projects to Node `>=18`
  .github/workflows/eslint.yml
  .github/workflows/nodejs-test.yml
  package.json
  pnpm-lock.yaml
  solardoc/asciidoc-renderer/package.json
  solardoc/asciidoc-renderer/pnpm-lock.yaml
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/phoenix-server/pnpm-lock.yaml
  solardoc/rest-api/package.json
  solardoc/rest-api/pnpm-lock.yaml
Labels: dependencies

#209 Fixed error on opening up a file in the profile view if the editor wasn't initialised yet
  solardoc/frontend/src/components/profile-view/header/ProfileViewHeaderButtons.vue
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/file.ts
  solardoc/frontend/src/scripts/editor/sds.ts
  solardoc/frontend/src/stores/current-file.ts
Labels: bug, fix
