Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2024-11, with the labels that each got.

#219 Add file user permissions
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/frontend/src/App.vue
  solardoc/frontend/src/components/collab/GlobalFileCard.vue
  solardoc/frontend/src/components/collab/GlobalFileList.vue
  solardoc/frontend/src/components/collab/GlobalFileSearch.vue
  solardoc/frontend/src/components/collab/GlobalFilesOverview.vue
  solardoc/frontend/src/components/common/InfoBox.vue
  solardoc/frontend/src/components/common/MinorProgressSpinner.vue
  solardoc/frontend/src/components/common/PaddedInfoBox.vue
  solardoc/frontend/src/components/common/TimeRef.vue
  solardoc/frontend/src/components/common/UserRef.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/CollaboratorCard.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/CollaboratorList.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/profile/files/FileCard.vue
  solardoc/frontend/src/scripts/collab/search.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/format-date.ts
  solardoc/frontend/src/scripts/handle-render.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/render/api-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/views/CollabView.vue
  solardoc/frontend/src/views/ShareURLView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/files.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/permissions.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/permissions/file_permission.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_confirmation_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_reset_password_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_settings_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/auth/user_auth_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/auth/user_auth_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/editor_channel/editor_channel_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/editor_channel/editor_channel_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_permission_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/home/home_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/ping/ping_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/share_url/share_url_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/share_url/share_url_json.ex
  solardoc/phoenix-server/priv/repo/migrations/20241031112026_create_file_permissions.exs
Labels: enhancement

#220 Added default example page for the editor
  solardoc/frontend/src/plugins/constants.ts
Labels: enhancement

#230 Fixed 500 response in `show_permissions_for_file`
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/phoenix-server/lib/solardoc_phoenix/permissions.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex
Labels: bug, fix

#235 Added option to change file name in file settings tab
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue
Labels: enhancement

#237 Added missing owner name and restylise file settings
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_json.ex
Labels: enhancement

#239 v1.0.0-dev.6 (Sprint 10)
  package.json
  pnpm-lock.yaml
  solardoc/asciidoc-renderer/package.json
  solardoc/asciidoc-renderer/pnpm-lock.yaml
  solardoc/asciidoc-renderer/src/index.ts
  solardoc/asciidoc-renderer/src/renderer/simulator/decktape-slim.ts
  solardoc/frontend/Dockerfile
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/components/editor/Editor.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue
  solardoc/frontend/src/components/editor/export/Export.vue
  solardoc/frontend/src/components/editor/sub-slides-navigator/SubSlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-views/default/DefaultEditorSubView.vue
  solardoc/frontend/src/components/editor/sub-views/default/slides-navigator/SlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/default/slides-navigator/SlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-views/default/sub-slides-navigator/SubSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/default/sub-slides-navigator/SubSlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-views/default/sub-slides-navigator/SubSlidesPreview.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-editor/FullScreenEditor.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/FullScreenSlidesManager.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/slides-navigator/SlidesManagerSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/slides-navigator/SlidesManagerSlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlideManagerSubSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlidesManagerSubSlidesNavigator.vue
  solardoc/frontend/src/components/icons/ArrowLeft.vue
  solardoc/frontend/src/components/icons/ArrowRight.vue
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/scripts/editor/file.ts
  solardoc/frontend/src/scripts/editor/sub-view-state.ts
  solardoc/frontend/src/scripts/handle-render.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/stores/last-modified.ts
  solardoc/frontend/src/stores/overlay-state.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/phoenix-server/Dockerfile
  solardoc/phoenix-server/lib/solardoc_phoenix/permissions.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_permission_controller.ex
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/package.json
  solardoc/postgresql-db/Dockerfile
  solardoc/postgresql-db/config/postgresql.conf
  solardoc/rest-api/Dockerfile
  solardoc/rest-api/package.json
  solardoc/rest-api/pnpm-lock.yaml
  solardoc/rest-api/public/favicon.ico
  solardoc/rest-api/src/controllers/v1/result.controller.ts
  solardoc/rest-api/src/index.ts
Labels: release

#242 Removed flat buttons and rearranged editor menu
  .run/Phoenix Server.run.xml
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/assets/main.scss
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/views/EditorView.vue
Labels: enhancement

#255 Improved visual clarity of file name input box in editor
  solardoc/frontend/src/assets/asciidoc.svg
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/components/icons/AsciidocIcon.vue
  solardoc/frontend/src/views/EditorView.vue
Labels: enhancement
