Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2024-12, with the labels that each got.

#256 Removed docs page
  solardoc/frontend/src/components/Navbar.vue
  solardoc/frontend/src/router/index.ts
  solardoc/frontend/src/views/DocsView.vue
  solardoc/frontend/src/views/HomeView.vue
Labels: maintenance

#258 Added upload button in save state indicator
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/components/icons/UploadIconSVG.vue
Labels: enhancement

#257 Added QR-Code generation to share url generation
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue
Labels: enhancement

#261 Replaced fullscreen button
  solardoc/frontend/src/components/icons/PresentationIconDarkModeSVG.vue
  solardoc/frontend/src/components/icons/PresentationIconSVG.vue
  solardoc/frontend/src/views/EditorView.vue
Labels: enhancement

#259 Optimised the website layout for phones and updated general website styling & backgrounds
  package.json
  solardoc/asciidoc-renderer/package.json
  solardoc/asciidoc-renderer/src/index.ts
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/frontend/src/App.vue
  solardoc/frontend/src/assets/core/_button.scss
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/assets/core/mixins/_hide.scss
  solardoc/frontend/src/assets/heart-background.scss
  solardoc/frontend/src/assets/main.scss
  solardoc/frontend/src/components/Footer.vue
  solardoc/frontend/src/components/Navbar.vue
  solardoc/frontend/src/components/collab/GlobalFileList.vue
  solardoc/frontend/src/components/collab/GlobalFileSearch.vue
  solardoc/frontend/src/components/common/PaddedInfoBox.vue
  solardoc/frontend/src/components/common/UserRef.vue
  solardoc/frontend/src/components/editor/FullScreenPreview.vue
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/editor-navbar/LastModified.vue
  solardoc/frontend/src/components/editor/sub-views/default/DefaultEditorSubView.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-editor/FullScreenEditor.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/FullScreenSlidesManager.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/slides-navigator/SlidesManagerSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/slides-navigator/SlidesManagerSlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlideManagerSubSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlidesManagerSubSlidesNavigator.vue
  solardoc/frontend/src/components/icons/AsciidocIcon.vue
  solardoc/frontend/src/components/icons/PresentationIconDarkModeSVG.vue
  solardoc/frontend/src/components/icons/PresentationIconSVG.vue
  solardoc/frontend/src/components/icons/UploadIconSVG.vue
  solardoc/frontend/src/components/navbar/Navbar.vue
  solardoc/frontend/src/components/navbar/NavbarOverlay.vue
  solardoc/frontend/src/components/profile/files/SearchBar.vue
  solardoc/frontend/src/components/profile/header/ProfileHeader.vue
  solardoc/frontend/src/components/profile/header/ProfileViewHeaderButtons.vue
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/views/CollabView.vue
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/HomeView.vue
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/ProfileView.vue
  solardoc/frontend/src/views/SignupView.vue
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/package.json
  solardoc/rest-api/package.json
Labels: enhancement, breaking change, critical

#260 Standardised file rename behaviour
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/sub-views/default/DefaultEditorSubView.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-editor/FullScreenEditor.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/FullScreenSlidesManager.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/slides-navigator/SlidesManagerSlidePreview.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/slides-navigator/SlidesManagerSlidesNavigator.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlidesManagerSubSlidesNavigator.vue
  solardoc/frontend/src/stores/current-file.ts
Labels: enhancement

#264 Removed PDF and JPG options in export menu
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/export/Export.vue
Labels: enhancement

#262 Add open in another window button and open printable view button
  solardoc/frontend/src/assets/core/_button.scss
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/assets/main.scss
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/editor-navbar/LastModified.vue
  solardoc/frontend/src/components/editor/editor-navbar/ViewInOtherWindowDropdown.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/FullScreenSlidesManager.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlidesManagerSubSlidesNavigator.vue
  solardoc/frontend/src/components/icons/PresentationIconSVG.vue
  solardoc/frontend/src/components/icons/ScreenIconDarkModeSVG.vue
  solardoc/frontend/src/components/icons/ScreenIconSVG.vue
  solardoc/frontend/src/components/navbar/Navbar.vue
Labels: enhancement
