Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2024-04, with the labels that each got.

#120 Fixed logout button bug in profile view and multiple text overflow bugs
  .gitignore
  solardoc/frontend/src/components/LoadAnywayButton.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelView.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelViewCreate.vue
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/services/phoenix/editor-channel.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/stores/file-name.ts
  solardoc/frontend/src/stores/file.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/ProfileView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/accounts/user_notifier.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/application.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/editor_channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/files.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/files/file.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_state.ex
  solardoc/phoenix-server/priv/repo/migrations/20240311232144_add_additional_user_properties.exs
  solardoc/phoenix-server/priv/repo/migrations/20240312211756_add_channel_auth.exs
  solardoc/phoenix-server/priv/repo/migrations/20240322073554_create_files.exs
  solardoc/phoenix-server/priv/repo/migrations/20240406142351_add_file_to_editor_channel.exs
  solardoc/phoenix-server/priv/repo/migrations/20240406144712_add_content_to_file.exs
  solardoc/phoenix-server/test/support/fixtures/files_fixtures.ex
Labels: bug, fix

#121 Implemented file server and file server api endpoints to store user account files
  .gitignore
  README.adoc
  images/Join-Create-Channel-Behaviour.drawio
  images/Join-Create-Channel-Behaviour.drawio.png
  package.json
  solardoc/asciidoc-renderer/package.json
  solardoc/asciidoc-renderer/src/index.ts
  solardoc/frontend/package.json
  solardoc/frontend/src/services/backend/gen/backend-rest-service.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/stores/current-user.ts
  solardoc/frontend/src/stores/file.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/ProfileView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/editor_channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/files.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/files/file.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/share.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/share/share_url.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/utils.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_state.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_trans.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/accounts/user_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/auth/user_auth_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/editor_channel/editor_channel_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/editor_channel/editor_channel_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/files/file_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/files/file_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/share_url/share_url_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/share_url/share_url_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/package.json
  solardoc/phoenix-server/priv/repo/migrations/20240322074530_create_share_urls.exs
  solardoc/phoenix-server/priv/repo/migrations/20240407131438_add_unique_index_for_file_name.exs
  solardoc/phoenix-server/priv/static/swagger.json
  solardoc/phoenix-server/test/solardoc_phoenix/files_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix/share_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix_web/controllers/file_controller_test.exs
  solardoc/phoenix-server/test/solardoc_phoenix_web/controllers/share_url_controller_test.exs
  solardoc/phoenix-server/test/support/fixtures/share_fixtures.ex
  solardoc/rest-api/package.json
  solardoc/rest-api/src/controllers/v1/render.controller.ts
  solardoc/rest-api/src/index.ts
  solardoc/rest-api/src/utils.ts
Labels: enhancement

#123 Fixed CORS error with localhost development environments
  .env.prod.template
  .env.template
  docker-compose.yaml
  solardoc/frontend/.env.dev.template
  solardoc/frontend/.env.prod.template
  solardoc/frontend/.env.template
  solardoc/frontend/src/config/import-meta-env.d.ts
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/services/phoenix/config.ts
  solardoc/phoenix-server/config/runtime.exs
  solardoc/phoenix-server/lib/solardoc_phoenix_web/endpoint.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/mix.lock
  solardoc/phoenix-server/priv/static/favicon.ico
Labels: bug, fix

#124 Added option in sandwich menu to save file in editor save status indicator
  solardoc/frontend/src/components/LoadAnywayButton.vue
  solardoc/frontend/src/components/editor/Editor.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelViewCreate.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/scripts/handle-render.ts
  solardoc/frontend/src/services/backend/gen/backend-rest-service.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/stores/editor-content.ts
  solardoc/frontend/src/stores/file.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/files/file_controller.ex
Labels: enhancement

#127 Implemented OT state management for the frontend and backend websocket
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/frontend/src/assets/core/_button.scss
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/assets/tooltip.scss
  solardoc/frontend/src/components/LoadAnywayButton.vue
  solardoc/frontend/src/components/editor/Editor.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelView.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelViewCreate.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelViewCurrent.vue
  solardoc/frontend/src/components/editor/channel-view/ChannelViewJoinConfirm.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/directives/tooltip.ts
  solardoc/frontend/src/main.ts
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/scripts/handle-ot.ts
  solardoc/frontend/src/services/backend/gen/backend-rest-service.ts
  solardoc/frontend/src/services/phoenix/editor-channel.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/phoenix/ot-trans.ts
  solardoc/frontend/src/services/phoenix/update-cycle-handler.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/stores/editor-update-ws-client.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/SignupView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/accounts/user.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_state.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_trans.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/files/file_controller.ex
Labels: enhancement

#125 Implemented generate share URL button for user presentations
  solardoc/frontend/package.json
  solardoc/frontend/pnpm-lock.yaml
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/editor/share-url/ShareUrlCreate.vue
  solardoc/frontend/src/config/import-meta-env.d.ts
  solardoc/frontend/src/main.ts
  solardoc/frontend/src/router/index.ts
  solardoc/frontend/src/scripts/handle-copy.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/stores/overlay-state.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/ShareURLView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/share.ex
  solardoc/phoenix-server/lib/solardoc_phoenix/share/share_url.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/share_url/share_url_controller.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/controllers/share_url/share_url_json.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/router.ex
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/mix.lock
  solardoc/phoenix-server/priv/repo/migrations/20240322074530_create_share_urls.exs
Labels: enhancement

#132 Implemented new file button which clears the current file and opens up a new local file
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
Labels: enhancement

#134 Created elixir.yml workflow
  .github/workflows/elixir.yml
Labels: other, maintenance
