Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2025-03, with the labels that each got.

#280 Implemented client-side transformation optimisations to reduce latency-induced update consistency clashes
  images/Optimised-Sync-Algorithm.drawio
  images/Optimised-Sync-Algorithm.drawio.png
  solardoc/asciidoc-renderer/src/renderer/simulator/plugins/reveal-plugin.ts
  solardoc/frontend/src/common/async-lock.ts
  solardoc/frontend/src/common/format-date.ts
  solardoc/frontend/src/common/index.ts
  solardoc/frontend/src/common/wait-for.ts
  solardoc/frontend/src/components/common/LoadingProgressSpinner.vue
  solardoc/frontend/src/components/common/TimeRef.vue
  solardoc/frontend/src/components/editor/ContributorsCount.vue
  solardoc/frontend/src/components/editor/dropdown/current-channel/CurrentChannel.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/editor-navbar/LastModified.vue
  solardoc/frontend/src/scripts/channel/join-channel.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/ot/create-ot.ts
  solardoc/frontend/src/scripts/editor/ot/get-monaco-updates.ts
  solardoc/frontend/src/scripts/editor/ot/send-ot.ts
  solardoc/frontend/src/scripts/editor/render.ts
  solardoc/frontend/src/services/phoenix/api-service.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/phoenix/ot-trans.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/services/render/api-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/views/HomeView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/files/file.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_controller.ex
  solardoc/phoenix-server/priv/repo/migrations/20250302145843_add_new_sync_algorithm_file_flag.exs
Labels: enhancement, critical

#283 Fixed incorrect UTF16 handling and implemented a custom OT insert & delete algorithm
  solardoc/frontend/src/main.ts
  solardoc/frontend/src/router/index.ts
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_state.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/utf16_comp.ex
Labels: bug, fix, breaking change

#284 v1.0.0-beta.8 (Sprint 13)
  images/Optimised-Sync-Algorithm.drawio
  images/Optimised-Sync-Algorithm.drawio.png
  package.json
  solardoc/asciidoc-renderer/package.json
  solardoc/asciidoc-renderer/src/index.ts
  solardoc/asciidoc-renderer/src/renderer/simulator/plugins/reveal-plugin.ts
  solardoc/frontend/package.json
  solardoc/frontend/src/common/async-lock.ts
  solardoc/frontend/src/common/format-date.ts
  solardoc/frontend/src/common/index.ts
  solardoc/frontend/src/common/wait-for.ts
  solardoc/frontend/src/components/common/LoadingProgressSpinner.vue
  solardoc/frontend/src/components/common/TimeRef.vue
  solardoc/frontend/src/components/editor/ContributorsCount.vue
  solardoc/frontend/src/components/editor/dropdown/current-channel/CurrentChannel.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/editor-navbar/LastModified.vue
  solardoc/frontend/src/components/editor/sub-views/default/DefaultEditorSubView.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-editor/FullScreenEditor.vue
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/FullScreenSlidesManager.vue
  solardoc/frontend/src/components/navbar/Navbar.vue
  solardoc/frontend/src/main.ts
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/router/index.ts
  solardoc/frontend/src/scripts/channel/join-channel.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/ot/create-ot.ts
  solardoc/frontend/src/scripts/editor/ot/get-monaco-updates.ts
  solardoc/frontend/src/scripts/editor/ot/send-ot.ts
  solardoc/frontend/src/scripts/editor/render.ts
  solardoc/frontend/src/services/phoenix/api-service.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/phoenix/ot-trans.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/services/render/api-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/HomeView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix/files/file.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/editor_channel_state.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/channels/utf16_comp.ex
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/files/file_controller.ex
  solardoc/phoenix-server/mix.exs
  solardoc/phoenix-server/package.json
  solardoc/phoenix-server/priv/repo/migrations/20250302145843_add_new_sync_algorithm_file_flag.exs
  solardoc/rest-api/package.json
Labels: release

#286 Fixed upload bug in save state upload button
  solardoc/frontend/src/components/editor/SaveStateBadge.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/navbar/Navbar.vue
  solardoc/frontend/src/main.ts
  solardoc/frontend/src/router/index.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/upload.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/views/EditorView.vue
Labels: bug, fix

#282 Removed `restart: always` from docker compose
  docker-compose.yaml
Labels: bug, fix
