Repository SYP-AHIF-2023-24-25/SolarDoc, pull requests merged in 2025-01, with the labels that each got.

#270 Added proper feature cards on the homepage
  solardoc/frontend/src/components/home/HomeFeatureCard.vue
  solardoc/frontend/src/views/HomeView.vue
Labels: enhancement

#273 Fixed bug causing combined Delete & Insert to break the local OT system
  .run/Phoenix Server.run.xml
  .run/build.run.xml
  .run/frontend _ dev.run.xml
  .run/prettier.run.xml
  .run/test-no-rebuild.run.xml
  .run/test.run.xml
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/scripts/async-lock.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/ot/send-ot.ts
  solardoc/frontend/src/services/phoenix/ot-trans.ts
  solardoc/frontend/src/services/phoenix/ws-client.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/stores/editor-update-ws-client.ts
Labels: bug, fix

#275 Implemented proper separation of local, remote and shared files
  docker-compose.yaml
  solardoc/frontend/src/App.vue
  solardoc/frontend/src/components/editor/dropdown/EditorSandwichDropdown.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/CollaboratorList.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue
  solardoc/frontend/src/components/editor/export/Export.vue
  solardoc/frontend/src/errors/file-not-found-error.ts
  solardoc/frontend/src/errors/not-implemented-error.ts
  solardoc/frontend/src/plugins/constants.ts
  solardoc/frontend/src/router/404-err.ts
  solardoc/frontend/src/router/index.ts
  solardoc/frontend/src/router/omit-query.ts
  solardoc/frontend/src/router/open.ts
  solardoc/frontend/src/scripts/editor/editor.ts
  solardoc/frontend/src/scripts/editor/file.ts
  solardoc/frontend/src/scripts/share/resolve-share-url.ts
  solardoc/frontend/src/scripts/show-notif.ts
  solardoc/frontend/src/scripts/wait-for.ts
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
  solardoc/frontend/src/stores/current-file.ts
  solardoc/frontend/src/views/EditorView.vue
  solardoc/frontend/src/views/ShareURLView.vue
  solardoc/rest-api/Dockerfile
Labels: bug, enhancement, fix, breaking change

#263 Auto-login when registering a new user
  .gitignore
  images/1280x640-github-banner-alt.png
  solardoc/frontend/src/router/index.ts
  solardoc/frontend/src/router/redirect.ts
  solardoc/frontend/src/views/LoginView.vue
  solardoc/frontend/src/views/ProfileView.vue
  solardoc/frontend/src/views/SignupView.vue
  solardoc/phoenix-server/lib/solardoc_phoenix_web/v2/controllers/accounts/user_controller.ex
Labels: enhancement

#265 Add collaborator count display to the editor
  .gitignore
  solardoc/frontend/public/404.html
  solardoc/frontend/src/assets/core/_var.scss
  solardoc/frontend/src/components/editor/ContributorsCount.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/CollaboratorCard.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/icons/PersonCountIconDarkModeSVG.vue
  solardoc/frontend/src/components/icons/PersonCountIconSVG.vue
  solardoc/frontend/src/services/phoenix/errors.ts
  solardoc/frontend/src/stores/contributors.ts
  solardoc/frontend/src/stores/file-owner.ts
  solardoc/frontend/src/views/ProfileView.vue
Labels: enhancement

#269 Fixed default slide manager scroll bug
  solardoc/frontend/src/components/editor/sub-views/default/slides-navigator/SlidesNavigator.vue
Labels: bug, fix

#274 Added save button to the file name if it got changed
  solardoc/frontend/src/components/collab/GlobalFileCard.vue
  solardoc/frontend/src/components/editor/FullScreenPreview.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/CollaboratorCard.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/CollaboratorList.vue
  solardoc/frontend/src/components/editor/dropdown/editor-settings/EditorSettings.vue
  solardoc/frontend/src/components/editor/dropdown/share-url/ShareUrlCreate.vue
  solardoc/frontend/src/components/editor/editor-navbar/EditorNavbar.vue
  solardoc/frontend/src/components/editor/editor-navbar/ViewInOtherWindowDropdown.vue
  solardoc/frontend/src/components/icons/SaveIconDarkModeSVG.vue
  solardoc/frontend/src/components/icons/SaveIconSVG.vue
  solardoc/frontend/src/components/navbar/NavbarOverlay.vue
  solardoc/frontend/src/components/profile/files/FileCard.vue
  solardoc/frontend/src/services/phoenix/gen/phoenix-rest-service.ts
  solardoc/frontend/src/services/render/gen/backend-rest-service.ts
Labels: enhancement

#277 Fixed phone subslides viewer slide index starting at 0 instead of 1
  solardoc/frontend/src/components/editor/sub-views/full-screen-slides-manager/sub-slides-navigator/SlidesManagerSubSlidesNavigator.vue
Labels: bug, fix
